<?php defined('ABSPATH') || exit; ?>
<section class="hero" aria-labelledby="hero-title" data-motion-hero>
  <div class="hero-atmosphere" aria-hidden="true"><div class="hero-aura"></div><div class="hero-cursor-glow"></div><div class="hero-grid-field"></div></div>
  <div class="container">
  <div class="hero-brand-stage">
    <p class="eyebrow hero-eyebrow"><span class="little-cross" aria-hidden="true">+</span> <span class="i18n-text"><?php float_theme_home('heroEyebrow'); ?></span></p>
    <h1 class="hero-wordmark" id="hero-title" lang="en" aria-label="FLOAT" data-interactive-wordmark><span class="hero-letter" aria-hidden="true"><span class="hero-letter-ink" data-letter="F">F</span></span><span class="hero-letter" aria-hidden="true"><span class="hero-letter-ink" data-letter="L">L</span></span><span class="hero-letter" aria-hidden="true"><span class="hero-letter-ink" data-letter="O">O</span></span><span class="hero-letter" aria-hidden="true"><span class="hero-letter-ink" data-letter="A">A</span></span><span class="hero-letter" aria-hidden="true"><span class="hero-letter-ink" data-letter="T">T</span></span></h1>
  </div>
  <div class="hero-grid"><div class="hero-copy"><p class="hero-statement"><span class="i18n-text"><?php float_theme_home('heroStatement1'); ?></span> <span class="muted-word"><span class="i18n-text"><?php float_theme_home('heroStatement2'); ?></span><span class="hero-period">.</span></span></p><p class="hero-subtitle"><span class="i18n-text"><?php float_theme_home('heroSubtitle1'); ?></span><br><span class="i18n-text"><?php float_theme_home('heroSubtitle2'); ?></span></p><p class="hero-note"><span class="i18n-text"><?php float_theme_home('heroNote1'); ?></span><br><span class="i18n-text"><?php float_theme_home('heroNote2'); ?></span></p><div class="hero-actions"><a class="button button-primary" href="#projects"><span class="i18n-text" data-i18n="t95e83f6af248">探索项目</span> <span aria-hidden="true">↘</span></a><?php if (float_theme_github()) : ?><a class="text-link" href="<?php echo float_theme_github(); ?>" target="_blank" rel="noopener noreferrer">GitHub <span aria-hidden="true">↗</span><span class="sr-only" data-i18n="t1d1833565142">（在新标签页打开）</span></a><?php endif; ?></div></div>
  <div class="hero-art" aria-hidden="true"><div class="orbital-ring ring-outer"></div><div class="orbital-ring ring-inner"></div><div class="hero-dot-field"></div><img class="hero-symbol" src="<?php echo esc_url(float_theme_asset('logo.svg')); ?>" alt="" width="320" height="320"><span class="art-cross cross-top">+</span><span class="art-cross cross-bottom">+</span><span class="art-coordinates" data-i18n="t8d6117950fdd">想法 → 做出来</span></div></div>
  <div class="hero-baseline"><span class="micro" data-i18n="t0fa8ca5ff109">互联网里的一小块空间。</span><a href="#projects"><span class="i18n-text" data-i18n="t291873e31ccb">向下探索</span> <span aria-hidden="true">↓</span></a><span class="micro" data-i18n="ta1515e4a121e">持续探索</span></div>
</div></section>
