<?php defined('ABSPATH') || exit; ?>
<section class="detail-showcase container" aria-label="硬件与界面示意" data-i18n-aria-label="t3801bbeb457c"><figure class="detail-device-figure"><div class="device-art" aria-hidden="true"><div class="device-shadow"></div><div class="device-shell"><img src="<?php echo esc_url(float_theme_asset('images/device.svg')); ?>" alt="" width="605" height="931" loading="lazy" decoding="async"><div class="device-ui"><div class="device-topline"><span data-i18n="t709276c8392f">概览</span><span>●</span></div><div class="device-host">DEMO DEVICE</div><div class="device-status" data-i18n="t9cce2c39dbb6">WSS / 示例</div>
<div class="device-metric"><span>CPU</span><b>28%</b><i class="cpu-fill"></i></div><div class="device-metric"><span>RAM</span><b>42%</b><i class="ram-fill"></i></div><div class="device-metric"><span data-i18n="t8267b044f191">磁盘</span><b>61%</b><i class="disk-fill"></i></div><div class="device-network">↓ 2.4 MB/s<br>↑ 0.8 MB/s</div><div class="device-bottom"><span class="i18n-text" data-i18n="t516305e6efcb">01 / 项目概览</span> <span>85%</span></div></div></div><span class="device-mark mark-one">+</span><span class="device-mark mark-two">+</span></div><figcaption data-i18n="td96e859e4028">原创设备插画 · 屏幕内容为虚构示例</figcaption></figure><figure class="detail-demo-figure"><div class="monitor-demo" data-monitor-demo>
  <div class="demo-heading"><span class="micro" data-i18n="ted3378998d31">DEMO DEVICE / 监控</span><span class="status-tag"><span class="status-dot"></span> <span class="i18n-text" data-i18n="teb13583bcda6">示例数据</span></span></div>
  <div class="monitor-tabs" role="tablist" aria-label="监控示例视图" data-i18n-aria-label="tf41260ab1fd6"><button type="button" role="tab" id="tab-overview" data-monitor-tab="overview" aria-selected="true" aria-controls="monitor-overview" data-i18n="td4b1ea5708dd">概览</button><button type="button" role="tab" id="tab-performance" data-monitor-tab="performance" aria-selected="false" aria-controls="monitor-performance" tabindex="-1" data-i18n="t442aded87a55">性能</button><button type="button" role="tab" id="tab-network" data-monitor-tab="network" aria-selected="false" aria-controls="monitor-network" tabindex="-1" data-i18n="t1744b96470b5">网络</button></div>
  <div class="monitor-panel" role="tabpanel" id="monitor-overview" aria-labelledby="tab-overview" tabindex="0"><div class="metric"><div><span>CPU</span><strong data-metric="cpu">28<span>%</span></strong></div><div class="metric-track"><span class="cpu-fill" data-fill="cpu"></span></div></div><div class="metric"><div><span data-i18n="tc3963aedaac6">内存</span><strong data-metric="ram">42<span>%</span></strong></div><div class="metric-track"><span class="ram-fill" data-fill="ram"></span></div></div><div class="metric"><div><span data-i18n="t340e0cf3bfa8">磁盘</span><strong data-metric="disk">61<span>%</span></strong></div><div class="metric-track"><span class="disk-fill" data-fill="disk"></span></div></div></div>
  <div class="monitor-panel" role="tabpanel" id="monitor-performance" aria-labelledby="tab-performance" tabindex="0" hidden><div class="performance-reading"><span data-i18n="ta8d93ffb16e3">CPU 历史 / 示例</span><strong data-performance-cpu>28%</strong></div><div class="sample-chart" role="img" aria-label="CPU 历史示意图，数值为虚构示例" data-i18n-aria-label="ta5581af0a18f"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><p class="micro chart-caption" data-i18n="tf6cdd15dc7d5">一小段历史，一眼便知。</p></div>
  <div class="monitor-panel" role="tabpanel" id="monitor-network" aria-labelledby="tab-network" tabindex="0" hidden><dl class="network-readings"><div><dt data-i18n="taaead4abf5d0">传输协议</dt><dd>WSS</dd></div><div><dt data-i18n="tbac9d15ad9f1">接收</dt><dd data-network-rx>2.4 MB/s</dd></div><div><dt data-i18n="t43b981c9c6d5">发送</dt><dd data-network-tx>0.8 MB/s</dd></div><div><dt data-i18n="t325e84939c64">后备连接</dt><dd>HTTPS</dd></div></dl></div>
  <div class="demo-foot"><span data-sample-index aria-live="polite" data-i18n="td2829985b90d">示例 01 / 03</span><button class="quiet-button" type="button" data-next-sample data-i18n="ta01b7858b534">下一组示例 →</button></div>
</div><figcaption><span class="i18n-text" data-i18n="t453e754427ce">切换三种概念视图，或逐组查看虚构的指标示例。</span><br><span data-i18n="t9064f7baa04d">网页界面为示意，数据均为虚构。实际固件界面可能不同。</span></figcaption></figure></section>
